language: go
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.12.x
    - go: 1.11.x
    - go: 1.10.x
    - go: 1.9.x
    - go: tip
  allow_failures:
    - go: tip

env:
  global:
    - DEP_VERSION="0.5.0"

branches:
  except:
  # Don't build Travis CI tags
  # MMDDyyyy-shortCommitHash
  - /[0-9]{8}-[0-9a-f]{7}/

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
    -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get -u github.com/gobuffalo/packr/v2/packr2

install:
  - dep ensure -v
  - cd $GOPATH/src/github.com/oipwg/oip/cmd/oipd && packr2 -v && cd -

cache:
  directories:
  - "$GOPATH/pkg/dep"

script:
  - go test -v -race ./...
  # Only build binaries from the latest Go release.
  - if [ "${LATEST}" = "true" ]; then
    env GOOS=darwin GOARCH=amd64 go build -ldflags
    "-X github.com/oipwg/oip/version.GitCommitHash=$(git rev-parse --short HEAD)
    -X github.com/oipwg/oip/version.BuildDate=$(date +'%Y.%m.%d.%H%M%S')
    -X github.com/oipwg/oip/version.BuiltBy=TravisCI
    -X 'github.com/oipwg/oip/version.GoVersion=$(go version)'
    -s -w" -o oipd github.com/oipwg/oip/cmd/oipd &&
    tar -czvf oipd.darwin.amd64.tar.gz oipd ;
    fi
  - if [ "${LATEST}" = "true" ]; then
    env GOOS=linux GOARCH=amd64 go build -ldflags
    "-X github.com/oipwg/oip/version.GitCommitHash=$(git rev-parse --short HEAD)
    -X github.com/oipwg/oip/version.BuildDate=$(date +'%Y.%m.%d.%H%M%S')
    -X github.com/oipwg/oip/version.BuiltBy=TravisCI
    -X 'github.com/oipwg/oip/version.GoVersion=$(go version)'
    -s -w" -o oipd github.com/oipwg/oip/cmd/oipd &&
    tar -czvf oipd.linux.amd64.tar.gz oipd ;
    fi
  - if [ "${LATEST}" = "true" ]; then
    env GOOS=windows GOARCH=amd64 go build -ldflags
    "-X github.com/oipwg/oip/version.GitCommitHash=$(git rev-parse --short HEAD)
    -X github.com/oipwg/oip/version.BuildDate=$(date +'%Y.%m.%d.%H%M%S')
    -X github.com/oipwg/oip/version.BuiltBy=TravisCI
    -X 'github.com/oipwg/oip/version.GoVersion=$(go version)'
    -s -w" -o oipd.exe github.com/oipwg/oip/cmd/oipd &&
    zip oipd.windows.amd64.zip oipd.exe ;
    fi

before_deploy:
  - git config --local user.name "Jenny Ruok"
  - git config --local user.email "41490681+jennyruok@users.noreply.github.com"
  - git tag -a "$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" -m "tagged by Travis-CI"

deploy:
  provider: releases
  skip_cleanup: true
  target_commitish: $TRAVIS_COMMIT
  api_key:
    secure: lr3LZU+AYBPbz2uiJQPTpze7XwbG4euLeU+uYs5BN+FqvGkl98w2WzYxCn/E3TcmZSDmTzYHFB99NnZ6nCwXrWB1HNqJe0u9ynM3Ccib81ARGw9Zt8PFRXAIRokrwNHLmHEyqiTbsx9mEbJWBp1VGkag5vXRQeA6rjZtxQYVOGBi4abqZ/eo+oAdOkI6Fe/hd0hBPkDREwkhAQsMo57VtzXr7gwIv+Cx4zBmegnyBbYFp3kPjePSpHmpsT2ojBBxjIpZmff08Z9aNdbPKMPvQUKSdZVJczJozmXs6wklx2kEAGpCuNP0Uv2xPREGhPn8DACOdLTDHHNaKVMyXlWTiFyTPjeK3B6HmmL8o47TpXbIjJnq3LAlpcBZz0wjNjwqF4USBD1VJVswY5x+IuT5DcsAM9PJg1ZaRBy3cfSjKzGG1d1h4eRWyyEITHptuLzBgUPT2waZKkgORezraZxiC3Z75rbjY2HxEI97bFOt80aBQ4igF/unUizs2lgzQUu1wIBG1SnB0tp5OQn4TP/xFW/rgHqNwe95qz14n9ojtb+2r7Gytf55BVjFqzgvLcQzYTt2GwkOQk1Q9xm31MKHw0UfCGidNYDMeMM0Evo7PG6AND6UEtZbReJcF5/KTEX/d9X2HHgxZiRW00sHQ7gCw3g0FDqcJiXUPPUxhJ1nJ1k=
  file:
    - oipd.darwin.amd64.tar.gz
    - oipd.linux.amd64.tar.gz
    - oipd.windows.amd64.zip
  prerelease: true
  on:
    branch: build
    repo: bitspill/oip
    condition: $LATEST = true

# go-critic update changed how it's run
# "For most users, using go-critic under golangci-lint is enough."
# https://github.com/golangci/golangci-lint
# after_script:
#   - go get -u github.com/go-critic/go-critic/...
#   - gocritic check-package -withExperimental -withOpinionated $(go list ./...)
